#Velocity playtime logger placeholderAPI extension.
file-version: 3
Messages:
  LOADING: "loading..."
  NOT_IN_TOPLIST: "Not in toplist"
Data:
  CHECK_FOR_UPDATES: true
  BSTATS: true
#Same as in the main plugin. ([space]'time in millisecs': cmd) (ex: '10000': say hello)
Rewards: